name: msbuild-vstest-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FOLDER: ./microsoft-cpp/cpp-unit-test-simple-dll/
  TEST_OUTPUT_FOLDER: ./microsoft-cpp/cpp-unit-test-simple-dll/test/simple-dll-test/bin/

permissions:
  contents: read
  
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release] # [Release, Debug]
        platform: [x64] # [x64, x86]

    steps:
    - name: Print the test output folder
      run: echo ${{env.TEST_OUTPUT_FOLDER}}${{matrix.configuration}}/${{matrix.platform}}/

    - name: Checkout
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FOLDER}}

    # execute msbuild for the specified configuration and platform
    - name: MSBuild
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FOLDER}}

    # run vstest on all generated test dlls
    - name: Run tests
      uses: microsoft/vstest-action@v0.1.0
      id: vstest
      with:
        testAssembly: '*-test.dll'
        searchFolder: ${{env.TEST_OUTPUT_FOLDER}}${{matrix.configuration}}/${{matrix.platform}}/
        resultsDirectory: ${{env.TEST_OUTPUT_FOLDER}}${{matrix.configuration}}/${{matrix.platform}}/test-results
        
    # Parse trx files
    - name: Parse Trx files
      uses: NasAmin/trx-parser@v0.1
      id: trx-parser
      with:
        TRX_PATH: ${{env.TEST_OUTPUT_FOLDER}}${{matrix.configuration}}/${{matrix.platform}}/test-results
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
